version: '2'
services:
  consul:
    image: "gliderlabs/consul-server"
    command: "-server -bootstrap"
    hostname: consul
    container_name: consul
    ports:
     - "8400:8400"
     - "8500:8500"
     - "172.17.0.1:53:8600/udp"
    networks:
     - my_net
  registrator:
    image: "gliderlabs/registrator"
    command: "-internal consul://172.17.0.1:8500"
    container_name: registrator
    hostname: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul
    networks:
     - my_net
  db:
    image: "mysql:5.5"
    container_name: mysql
    hostname: mysql
    volumes:
#      - ./data:/var/lib/mysql
       - ./mydb:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: root
    depends_on:
      - registrator
    ports:
      - 3306:3306
    networks:
     - my_net
  web:
    build: .
    depends_on:
      - db
      - consul
    ports:
     - 8080:8080
    volumes:
      - .:/code
    networks:
     - my_net
networks:
  my_net:
    driver: bridge
